### ISSUE TITLE
Issue importing current sqlite SDE

### ISSUE THREAD

**Issue by zerfall** [madcowfred/evething#107]
```
$ python import.py
=> Region: 100 (0.49s)
=> Constellation: 1120 (0.26s)
=> System: 8035 (1.18s)
=> Station: 5185 (1.57s)
=> MarketGroup: 1945 (181.11s)
=> ItemCategory: 40 (0.02s)
=> ItemGroup: 1069 (0.24s)
=> Item: ==> Invalid marketGroupID 354496
==> Invalid marketGroupID 354341
==> Invalid marketGroupID 354396
==> Invalid marketGroupID 354395
==> Invalid marketGroupID 356922
24481 (7.56s)
=> Implant: 732 (0.77s)
=> Blueprint:
Traceback (most recent call last):
  File "import.py", line 884, in <module>
    importer.import_all()
  File "import.py", line 118, in import_all
    time_func('Blueprint', self.import_blueprint)
  File "import.py", line 97, in time_func
    added = f()
  File "import.py", line 586, in import_blueprint
    self.cursor.execute('SELECT activityID, materialTypeID, quantity, consume FROM industryActivityMaterials WHERE typeID=%s', (id,))
  File "thingenv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "thingenv/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "thingenv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "thingenv/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 485, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: consume
```

**Comment by logical-fallacy** [comment]
Don't have time to do a pull request at the moment but they removed the 'consume' boolean from industryActivityMaterials in the SDE. All materials are consumed now. Here's a quick diff that will import everything with the value set to true:

``` diff
diff --git a/import.py b/import.py
index 4deafbd..f1d5de1 100755
--- a/import.py
+++ b/import.py
@@ -583,7 +583,7 @@ class Importer:
         new = []
         for id, data in bulk_data.items():
             # Base materials
-            self.cursor.execute('SELECT activityID, materialTypeID, quantity, consume FROM industryActivityMaterials WHERE typeID=%s', (id,))
+            self.cursor.execute('SELECT activityID, materialTypeID, quantity FROM industryActivityMaterials WHERE typeID=%s', (id,))
             for baserow in self.cursor:
                 # blueprint 3927 references itemId 3924 which doesn't exist,
                 # so ignore it, :ccp:
@@ -593,7 +593,7 @@ class Importer:
                         activity=baserow[0],
                         item_id=baserow[1],
                         count=baserow[2],
-                        consumed=baserow[3]
+                        consumed=True
                     ))
                     added += 1
         # If there's any new ones just drop and recreate the whole lot, easier
diff --git a/import_masteries.py b/import_masteries.py
index 76da3bc..02124f8 100755
```
