### ISSUE TITLE
Error when importing database data

### ISSUE THREAD

**Issue by AMoo** [madcowfred/evething#3]
Following the install info on a clean Debian install with Python 2.7.3rc2 and all of the other required modules (installed with the instructions, requirements.txt)

When I issue the command to import the database data I get an error.  The evething database seems to be partially populated and the syncdb command can't find a table that hasn't been created, throwing the error below.

~/thingeve/evething $ python import.py syncdb
=> Region:
Traceback (most recent call last):
  File "import.py", line 808, in <module>
    importer.import_all()
  File "import.py", line 67, in import_all
    time_func('Region', self.import_region)
  File "import.py", line 57, in time_func
    added = f()
  File "import.py", line 91, in import_region
    data_map = Region.objects.in_bulk(bulk_data.keys())
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/db/models/manager.py", line 158, in in_bulk
    return self.get_query_set().in_bulk(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/db/models/query.py", line 488, in in_bulk
    return dict([(obj._get_pk_val(), obj) for obj in qs])
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/db/models/query.py", line 118, in _result_iter
    self._fill_cache()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/db/models/query.py", line 875, in _fill_cache
    self._result_cache.append(self._iter.next())
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/db/models/query.py", line 291, in iterator
    for row in compiler.results_iter():
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/db/models/sql/compiler.py", line 763, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/db/models/sql/compiler.py", line 818, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/Django-1.4.1-py2.7.egg/django/db/backends/mysql/base.py", line 114, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python2.7/dist-packages/MySQL_python-1.2.3-py2.7-linux-armv6l.egg/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/dist-packages/MySQL_python-1.2.3-py2.7-linux-armv6l.egg/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.DatabaseError: (1146, "Table 'evething.thing_region' doesn't exist")

any ideas ?

**Comment by madcowfred** [comment]
Run 'python manage.py syncdb' like the README says, not import.py :( I've just updated the steps slightly after a somewhat related bug report, it should now be:
1. "python manage.py syncdb", say NO when it asks if you would like to create an admin user.
2. "python manage.py migrate --all", this will apply database migrations in order.
3. "python manage.py createsuperuser" to create a new superuser.

**Comment by AMoo** [comment]
OK got a bit further but then I get this when syncing the databases

> thing:0009_rename_apikey_id_to_keyid
> FATAL ERROR - The following SQL query failed: ALTER TABLE `thing_apikey` ADD COLUMN `id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY DEFAULT 0;

if you run that query manually it does indeed fail due to an invalid default value.

manually editing the thing/migrations 0009 file and deleting the default value solves this btw.

**Comment by spapin** [comment]
Are you using sqlite? Sqlite doesn t like the primary key with no.default
value. Try to.change the.migration function or to use.mysql or pstgresql as
a db server

**Comment by madcowfred** [comment]
I actually fixed that one yesterday in ccef747198e307a8167ce7deed734dab48d66780, SQLite is still evil but should work now.

**Comment by AMoo** [comment]
I'm actually using a wierd setup.  The SDE is a sqlite file and the evething database is mysql.  I got it working fine with the manual edit but I'm going to do another clean install with both databases in mysql tonight.

**Comment by AMoo** [comment]
Just did a mysql / mysql database install and the default=0 flag breaks that install too.  Again manually removing that flag in the 0009_rename_apikey_id_to_keyid.py file makes the install work.

**Comment by madcowfred** [comment]
I did some testing with this, apparently 0009 breaks in completely different ways on MySQL/Postgres/SQLite. Awesome. Sorting out a proper fix once MySQL finishes installing.

**Comment by madcowfred** [comment]
Fixed (and tested this time) in 0551c3c3b75f6abadf336699c8e6b523c077512e
