### ISSUE TITLE
Import.py cannot import 'item' (Incorrect string value)

### ISSUE THREAD

**Issue by Kyria** [madcowfred/evething#76]
I get the following error when importing (first time I get it...).

I tried : changing encoding of db (usually utf8 both) but don't change anything...

My versions : 
python 2.7.6
mysql 5.6.17

```
Traceback (most recent call last):
  File "import.py", line 853, in <module>
    importer.import_all()
  File "import.py", line 114, in import_all
    time_func('Item', self.import_item)
  File "import.py", line 95, in time_func
    added = f()
  File "import.py", line 458, in import_item
    Item.objects.bulk_create(new)
  File "/Users/Kyria/Coding/evething_env/lib/python2.7/site-packages/django/db/models/manager.py", line 160, in bulk_create
    return self.get_queryset().bulk_create(*args, **kwargs)
  File "/Users/Kyria/Coding/evething_env/lib/python2.7/site-packages/django/db/models/query.py", line 356, in bulk_create
    self._batched_insert(objs_with_pk, fields, batch_size)
  File "/Users/Kyria/Coding/evething_env/lib/python2.7/site-packages/django/db/models/query.py", line 838, in _batched_insert
    using=self.db)
  File "/Users/Kyria/Coding/evething_env/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/Users/Kyria/Coding/evething_env/lib/python2.7/site-packages/django/db/models/query.py", line 1514, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/Kyria/Coding/evething_env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 903, in execute_sql
    cursor.execute(sql, params)
  File "/Users/Kyria/Coding/evething_env/lib/python2.7/site-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/Kyria/Coding/evething_env/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/Users/Kyria/Coding/evething_env/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/Kyria/Coding/evething_env/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/Users/Kyria/Coding/evething_env/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/Users/Kyria/Coding/evething_env/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/Users/Kyria/Coding/evething_env/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1366, "Incorrect string value: '\\xE6\\xB3\\xB0\\xE5\\x9D\\xA6...' for column 'name' at row 992")
```

If someone have an idea, i'd appreciate as I didn't have this problem before... 

Regards

**Comment by Kyria** [comment]
Well... this issue can be closed. 

It was an error in my mysql config... (it was forcing latin1 in char fields). But the weird thing is that, prior to kronos, I had no issue with latin1... something might have change.
