### ISSUE TITLE
SQL error after adding key

### ISSUE THREAD

**Issue by AMoo** [madcowfred/evething#8]
Fresh install, clean database.  Added a character key and got the following error generated in my worker log file.

<pre>[2012-10-01 12:55:07,074: ERROR/MainProcess] Task thing.tasks.api_key_info[a9eee6a2-24fe-4ee4-8aa0-dbe64f8ce6e4] raised exception: IntegrityError(1452, 'Cannot add or update a child row: a foreign key constraint fails (`evething`.`thing_character`, CONSTRAINT `corporation_id_refs_id_5b74e5deccbfecc6` FOREIGN KEY (`corporation_id`) REFERENCES `thing_corporation` (`id`))')
Traceback (most recent call last):
  File "/thingenv/lib/python2.7/site-packages/celery/task/trace.py", line 224, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/thingenv/lib/python2.7/site-packages/celery/task/trace.py", line 403, in __protected_call__
    return self.run(*args, **kwargs)
  File "/thingenv/evething/thing/tasks.py", line 537, in api_key_info
    character.save()
  File "/thingenv/lib/python2.7/site-packages/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/thingenv/lib/python2.7/site-packages/django/db/models/base.py", line 551, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
  File "/thingenv/lib/python2.7/site-packages/django/db/models/manager.py", line 203, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/thingenv/lib/python2.7/site-packages/django/db/models/query.py", line 1576, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/thingenv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 910, in execute_sql
    cursor.execute(sql, params)
  File "/thingenv/lib/python2.7/site-packages/django/db/backends/util.py", line 40, in execute
    return self.cursor.execute(sql, params)
  File "/thingenv/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 114, in execute
    return self.cursor.execute(query, args)
  File "/thingenv/lib/python2.7/site-packages/MySQLdb/cursors.py", line 181, in execute
    self.errorhandler(self, exc, value)
  File "/thingenv/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`evething`.`thing_character`, CONSTRAINT `corporation_id_refs_id_5b74e5deccbfecc6` FOREIGN KEY (`corporation_id`) REFERENCES `thing_corporation` (`id`))')
</pre>

**Comment by spapin** [comment]
What database middleware are you using?

**Comment by AMoo** [comment]
mysql for both.

**Comment by AMoo** [comment]
hmmm, ok so I reimported the inferno database and then remigrated the info into thing and it seems to work as it's pulling character info now
