### ISSUE TITLE
cannot add a null=False column without a default value

### ISSUE THREAD

**Issue by mark-kubacki** [madcowfred/evething#9]
Using SQLite3 I get this:

```
$ python manage.py migrate --all

…
 > thing:0009_rename_apikey_id_to_keyid
Traceback (most recent call last):
  File "manage.py", line 19, in <module>
    execute_from_command_line(sys.argv)
  File "evething/thingenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "evething/thingenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "evething/thingenv/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "evething/thingenv/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "evething/thingenv/lib/python2.7/site-packages/south/management/commands/migrate.py", line 108, in handle
    ignore_ghosts = ignore_ghosts,
  File "evething/thingenv/lib/python2.7/site-packages/south/migration/__init__.py", line 213, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "evething/thingenv/lib/python2.7/site-packages/south/migration/migrators.py", line 235, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "evething/thingenv/lib/python2.7/site-packages/south/migration/migrators.py", line 310, in migrate_many
    result = self.migrate(migration, database)
  File "evething/thingenv/lib/python2.7/site-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration)
  File "evething/thingenv/lib/python2.7/site-packages/south/migration/migrators.py", line 106, in run
    dry_run.run_migration(migration)
  File "evething/thingenv/lib/python2.7/site-packages/south/migration/migrators.py", line 191, in run_migration
    self._run_migration(migration)
  File "evething/thingenv/lib/python2.7/site-packages/south/migration/migrators.py", line 178, in _run_migration
    raise exceptions.FailedDryRun(migration, sys.exc_info())
south.exceptions.FailedDryRun:  ! Error found during dry run of '0009_rename_apikey_id_to_keyid'! Aborting.
Traceback (most recent call last):
  File "evething/thingenv/lib/python2.7/site-packages/south/migration/migrators.py", line 175, in _run_migration
    migration_function()
  File "evething/thingenv/lib/python2.7/site-packages/south/migration/migrators.py", line 57, in <lambda>
    return (lambda: direction(orm))
  File "evething/thingenv/evething/thing/migrations/0009_rename_apikey_id_to_keyid.py", line 24, in forwards
    db.add_column('thing_apikey', 'id', models.AutoField(primary_key=True))
  File "evething/thingenv/lib/python2.7/site-packages/south/db/sqlite3.py", line 25, in add_column
    raise ValueError("You cannot add a null=False column without a default value.")
ValueError: You cannot add a null=False column without a default value.
```

**Comment by madcowfred** [comment]
I hate this stupid migration. Possibly fixed in bc22536463 :(

**Comment by spapin** [comment]
I recall the fix might break the migration on mysql. Better check it.

**Comment by martinvol** [comment]
I ended up with the same problem today. Anyone know a way to fix this temporally?

**Comment by madcowfred** [comment]
If you've actually updated the tree (develop branch!) in the last week and still get an error... I have no idea. I just made a test sqlite3 database with Python 2.7 and migrations apply perfectly happily on current develop tree:
- Migrating forwards to 0042_auto__add_tasksummary.
- (stuff here)
- > thing:0009_rename_apikey_id_to_keyid
- > thing:0010_add_apikey_characters_m2m_table
